name:                typelevel
version:             0.1.0.0
github:              "githubuser/typelevel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/typelevel#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- text
- text-show
- mtl
- QuickCheck

default-extensions:
- OverloadedStrings
- DataKinds
- PolyKinds
- TypeFamilies
- ScopedTypeVariables
- KindSignatures
- TypeApplications
- TypeOperators
- AllowAmbiguousTypes
- ExplicitForAll
- GADTs
- GADTSyntax
- NoStarIsType
- ConstraintKinds
- UndecidableInstances
- FlexibleInstances
- RankNTypes
- InstanceSigs

library:
  source-dirs: src

executables:
  typelevel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel

tests:
  typelevel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel
